services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - target: 5432
        published: 55432
        protocol: tcp
    volumes:
      - postgresql:/var/lib/postgresql/data
    # PostGIS 설치를 위한 초기화 스크립트 추가
    command:  >
      bash -c "apt-get update &&
                     apt-get install -y postgis postgresql-16-postgis-3 &&
                     rm -rf /var/lib/apt/lists/* &&
                     docker-entrypoint.sh postgres"
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  postgresql:
  minio-data: