services:
  pgvector:
    image: 'timescale/timescaledb-ha:pg16.9-ts2.20.0-oss'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - target: 5432
        published: 45432
        protocol: tcp
    volumes:
      - postgresql:/var/lib/postgresql/data
    # PostGIS 설치를 위한 초기화 스크립트 추가
    #command:  >
    #  bash -c '
    #  docker-entrypoint.sh postgres &
    #  until pg_isready -U myuser -d mydatabase; do sleep 1; done;
    #  psql -U myuser -d mydatabase -c "CREATE EXTENSION IF NOT EXISTS vector;" -c "CREATE EXTENSION IF NOT EXISTS postgis;"
    #  wait
    #  '
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  postgresql:
  minio-data: