import { StyleSheet } from "react-native";
import fonts from "../constants/fonts";

const styles = StyleSheet.create({
    container: {
        backgroundColor: "#F0F0D9",
        borderRadius: 12,
        padding: 16,
        marginHorizontal: 20,
        elevation: 2,
    },
    levelWrapper: {
        position: "absolute",
        top: 8,
        left: 12,
    },
    levelText: {
        fontSize: 35,
        fontFamily: fonts.laundryBold,
        marginTop: 15,
        marginLeft: 20,
        color: "#795548",
    },
    potImage: {
        height: 120,
        resizeMode: "contain",
        alignSelf: "center",
        marginTop: 20,
        marginBottom: 12,
    },
    progressWrapper: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 4,
        marginBottom: 8,
        marginHorizontal: 16,
    },
    progressButtonRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginHorizontal: 16,
        marginTop: 6,
    },
    progressContainer: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
        marginRight: 15,
    },
    progressBar: {
        flex: 1,
        height: 8,
        backgroundColor: "#81D4FA",
        borderRadius: 4,
    },
    progressText: {
        marginLeft: 8,
        fontSize: 12,
        color: "#333",
    },
    button: {
        backgroundColor: "#4FC3F7",
        paddingVertical: 11,
        paddingHorizontal: 16,
        borderRadius: 20,
        alignSelf: "flex-end",
        shadowColor: "#3186AD",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 10,
        shadowRadius: 0,
        elevation: 4,
    },
    buttonText: {
        fontSize: 15,
        letterSpacing: 0.25,
        color: "#fff",
        fontFamily: fonts.laundryBold,
    },
    buttonContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    waterIcon: {
        marginRight: 2,
        marginBottom: 0.5, // adjust vertical alignment slightly
    },
    infoModalContainer: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "flex-start",
        alignItems: "center",
    },
    infoBubble: {
        maxWidth: "90%",
        backgroundColor: "#fff",
        borderRadius: 20,
        padding: 12,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 4,
        position: "absolute",
        top: "30%", // changed to percentage for responsive layout
        left: "8.5%",
    },
    infoBubbleArrow: {
        position: "absolute",
        top: -16,
        right: "9%",
        width: 0,
        height: 0,
        borderLeftWidth: 8,
        borderRightWidth: 8,
        borderBottomWidth: 16,
        borderLeftColor: "transparent",
        borderRightColor: "transparent",
        borderBottomColor: "#fff",
        transform: [{ translateX: 12 }],
    },
    closeButton: {
        alignSelf: "flex-end",
        marginBottom: 8,
        marginRight: 8,
        paddingVertical: 4,
        paddingHorizontal: 8,
        backgroundColor: "#F6914D",
        borderRadius: 10,
    },
    closeButtonText: {
        color: "#fff",
        fontSize: 12,
        letterSpacing: 0.8,
        paddingHorizontal: 4,
        paddingVertical: 4,
        fontFamily: fonts.laundry,
    },
    infoBubbleText: {
        fontSize: 12,
        color: "#333",
        letterSpacing: 0.6,
        lineHeight: 18,
        fontFamily: fonts.laundry,
        paddingHorizontal: 20,
    },
    infoBubbleTitle: {
        fontSize: 16,
        letterSpacing: 0.8,
        color: "#333",
        fontFamily: fonts.laundryBold,
        paddingHorizontal: 20,
        marginTop: 20,
    },
});

export default styles;
