spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
jwt:
  signing-key: ${JWT_SIGNING_KEY}
  validate-key: ${JWT_VALIDATE_KEY}
  access-token-validity: 900
  refresh-token-validity: 604800
etc:
  host: ${HOST_NAME}
logging:
  level:
    root: INFO
    kr.ac.kookmin.wuung.security: OFF
s3:
  url: ${S3_URI}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  profile-bucket: ${S3_PROFILE_BUCKET}