spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      base-url: ${GPT_BASE_URL}
      api-key: ${GPT_API_KEY}
      chat:
        options:
          model: gpt-4o
  batch:
    jdbc:
      initialize-schema: embedded
    job:
      enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
jwt:
  signing-key: ${JWT_SIGNING_KEY}
  validate-key: ${JWT_VALIDATE_KEY}
  issuer: ${JWT_ISSUER}
  access-token-validity: 10800 # 원래 900초
  refresh-token-validity: 2592000
etc:
  host: ${HOST_NAME}
logging:
  level:
    root: INFO
    kr.ac.kookmin.wuung.security: OFF
s3:
  url: ${S3_URI}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  profile-bucket: ${S3_PROFILE_BUCKET}
  quest-bucket: ${S3_QUEST_BUCKET}
  public-endpoint: ${S3_PUBLIC_ENDPOINT}
app:
  package-name: ${PACKAGE_NAME}
  google-cloud-project-number: ${GOOGLE_CLOUD_PROJECT_NUMBER}
  google-cloud-api-key: ${GOOGLE_CLOUD_API_KEY}
  google-account-json: ${GOOGLE_ACCOUNT_JSON}
  apple-team-id: ${APPLE_TEAM_ID}
  apple-key-id: ${APPLE_KEY_ID}
snapadmin:
  enabled: true
  baseUrl: admin
  models-package: kr.ac.kookmin.wuung.model